### PR TITLE
Update icebergs to use fms2io

### PR DESCRIPTION
**Pull request by uramirez8707**
- This PR updates #63 after #64 was merged.
- The maro `use_depreciated_io` is used to control whether to use fms2_io or fms_io. The default is to use fms2_io. 
- There were so minor updates made to `icebergs.F90` (remove unused use statements) and `icebergs_framework.F90` (remove the `INTERNAL_FILE_NML` macro)
- This commit shows most of the changes between the fms2_io and fms_io version of icebergs_io.F90:https://github.com/uramirez8707/icebergs/commit/6938cf5714ccf034c90e4bbc4f166adc1a4f8454
- `icebergs_fmsio.F90` is exactly the same as icebergs_io.F90 in dev/gfdl (except for the module name change)
-  This was tested with SPEAR and the experiments `MOM6_GOLD_SIS2_bergs` and `MOM6_GOLD_SIS2_bergs_ens2`. Answers reproduce except for this:
```
DIFFER : VARIABLE : iceberg_counter_grd : TYPE : INT <> DOUBLE
```
The variable passed in to `register_diag_field` is an integer, which is why fms2_io is writitng it as an integer. The reason why fms_io writes it as a real is explained here: https://github.com/NOAA-GFDL/FMS/issues/1166

### CODE REVIEW

**Comment by uramirez8707** [comment]
FYI @marshallward @adcroft

**Comment by thomas-robinson** [comment]
@adcroft is there any feedback on this PR?  Can it be merged?

**Comment by adcroft** [comment]
Which version of FMS is needed for this to compile? I realized I hadn't toggled the CPP macro and I get
```
build/gnu/repro/icebergs/libicebergs.a: ../../../.././/src/icebergs/src/icebergs_fms2io.F90:18:5:
build/gnu/repro/icebergs/libicebergs.a: 
build/gnu/repro/icebergs/libicebergs.a:    18 | use fms2_io_mod, only: get_instance_filename
build/gnu/repro/icebergs/libicebergs.a:       |     1
build/gnu/repro/icebergs/libicebergs.a: Fatal Error: Cannot open module file 'fms2_io_mod.mod' for reading at (1): No such file or directory
```
when using 2023.01.01

**Comment by adcroft** [comment]
> Which version of FMS is needed for this to compile? I realized I hadn't toggled the CPP macro and I get
> ...

Nevermind: I had an out-of-date path_names file.

**Comment by adcroft** [comment]
Unfortunately I'm detecting a regression though I need to unravel whether that is coming from the iceberg code or FMS2. Will update when I get a chance to investigate ...

**Pull request merged**
